### ISSUE TITLE
Add support for authenticated ciphers such as GCM

### ISSUE THREAD

**Issue by jimbeaudoin** [rocketjob/symmetric-encryption#65]
I was trying to use the `aes-256-gcm` cipher but when I try to decrypt my data with it, I'm receiving an `OpenSSL::Cipher::CipherError`. I can encrypt without problems.

I was wondering if this is an issue with the gem or if I'm doing something wrong.

Is there something special we need to do to use this cipher? I'm using the same config as usual. Only the `cipher_name` is changed.

Thanks!

**Comment by reidmorrison** [comment]
Unfortunately switching to `GCM` is not quite as transparent as I had hoped. After further research changes will be required to Symmetric Encryption. My first step is better understand GCM and then to determine how we can implement it securely in Symmetric Encryption without any major changes to the API.

**Comment by ahugofonseca** [comment]
Hello people,

Are there any plans to launch GCM support yet?
I realized that this issue is open, and the [feature / gcm](https://github.com/rocketjob/symmetric-encryption/compare/feature/gcm) has not yet been merged.

When executing: `bundle exec symmetric-encryption -L | grep -i gcm` I realized that theoretically it already supports **AES-256-GCM**, however when trying to decrypt I get an exception:

``
OpenSSL :: Cipher :: CipherError:
from /home/hugo/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/symmetric-encryption-4.3.2/lib/symmetric_encryption/c
ipher.rb: 328: in `final '
``

Am I doing something wrong?
Could you show me a working example, or in fact it still doesn't support AES-256-GCM?

Thank you very much in advance!

**Comment by reidmorrison** [comment]
To get GCM support it just needs someone that wants to add it. The header already has support for it.
Want to submit a pull request?
I am available to answer any questions if you need help.

**Comment by reidmorrison** [comment]
GCM relies on a random IV with every new encryption stream. This is because it uses that same IV with a sequential counter to encrypt every block in that stream.

With CBC this is not nearly as much of an issue since the IV is only used on the very first block, instead of repeatedly for every block as in GCM.

As such it is not safe to implement GCM for Symmetric Encryption, since it does not enforce the use of a random IV.

Not using a random IV is required when using an encrypted value to locate records with the same encrypted value.
For example, find all records with the same bank account number, or social security number, when those values are encrypted. Using a random IV would make it impossible to find matching records since the encrypted value is always different.
