### ISSUE TITLE
OpenSSL::PKey::RSAError: data greater than mod len

### ISSUE THREAD

**Issue by ACPK** [rocketjob/symmetric-encryption#83]
I upgraded from 3.9.1 to 4.0.0 yesterday and now get:

    OpenSSL::PKey::RSAError: data greater than mod len
    remote:  !     /ruby/2.4.0/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/rsa_key.rb:17:in `private_decrypt'
    remote:  !     /ruby/2.4.0/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/rsa_key.rb:17:in `decrypt'
    remote:  !     /ruby/2.4.0/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/key.rb:49:in `migrate_config!'
    remote:  !     /ruby/2.4.0/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/cipher.rb:21:in `from_config'
    remote:  !     /ruby/2.4.0/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/config.rb:86:in `block in ciphers'
    remote:  !     /ruby/2.4.0/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/config.rb:86:in `collect'

**Comment by aruprakshit** [comment]
I am also getting the same error. Any idea why is that?

**Comment by reidmorrison** [comment]
You could try running the command line option to upgrade your configuration file and see if that helps. 

Unfortunately you cannot send us the encryption key files so that we can try to reproduce the issue locally.

Can you reproduce the issue with a standalone installation? I.e. with new key files that you will not use. Then we can run those locally to see if we can get the same error.

**Comment by reidmorrison** [comment]
Did running `symmetric-encryption --migrate` help?
